### ISSUE TITLE
Feature request: change background color of web view

### ISSUE THREAD

**Issue by maxgiraldo** [nks5117/KatexUtils#2]
I noticed that the background color is hard coded here: https://github.com/nks5117/KatexUtils/blob/0df3e93d227ed985c88ce234f80976c8dd4b483e/KatexUtils/Classes/KatexView.swift#L209

Would it be possible to expose this property or the web view itself as public so that it could be modified?

**Comment by nks5117** [comment]
Thanks for the comment.

Yes, I think it's a bad idea to hard code the background color. I've changed the `backgroundColor` property of the `KatexView`'s inner webview from `.white` to `.clear` in version 0.2.3. So now you can use the `KatexView`'s `backgroundColor` property just like any other views and get the right result.

Note that you may also want to change the font color of a `KatexView`, especially when a dark background is used. Because the formula is actually renderred in a webview context, so you may want to do this by modifing the `KatexView`'s `customCss` property.

I've also added some code to the example project to show how to use these newly added features.

Let me know if you have any further questions.

**Comment by maxgiraldo** [comment]
Amazing! Thank you for responding so quickly! I'll go ahead and close this issue then. Have a great rest of your week!
